
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'HA HIKU ID KARA NI NO NUMBER TASU VAR WOprog : sentencesentence : formula\n        | assign\n        | againstassign : VAR HA formulaassign : VAR NO VAR HA formulaagainst : VAR NI formula WO TASU\n        | VAR KARA formula WO HIKUagainst : VAR NO VAR NI formula WO TASU\n        | VAR NO VAR KARA formula WO HIKUformula : termterm : term TASU factor\n        | term HIKU factor\n        | factorfactor : NUMBERfactor : VARfactor : VAR NO VAR'
    
_lr_action_items = {'VAR':([0,10,11,12,13,14,15,23,24,25,26,],[7,17,17,17,20,17,17,29,17,17,17,]),'NUMBER':([0,10,11,12,14,15,24,25,26,],[9,9,9,9,9,9,9,9,9,]),'$end':([1,2,3,4,5,6,7,8,9,16,17,18,19,20,29,30,33,34,37,38,],[0,-1,-2,-3,-4,-11,-16,-14,-15,-12,-16,-13,-5,-17,-17,-6,-7,-8,-9,-10,]),'WO':([6,8,9,16,17,18,21,22,29,31,32,],[-11,-14,-15,-12,-16,-13,27,28,-17,35,36,]),'TASU':([6,7,8,9,16,17,18,20,27,29,35,],[10,-16,-14,-15,-12,-16,-13,-17,33,-17,37,]),'HIKU':([6,7,8,9,16,17,18,20,28,29,36,],[11,-16,-14,-15,-12,-16,-13,-17,34,-17,38,]),'HA':([7,20,],[12,24,]),'NO':([7,17,],[13,23,]),'NI':([7,20,],[14,25,]),'KARA':([7,20,],[15,26,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'prog':([0,],[1,]),'sentence':([0,],[2,]),'formula':([0,12,14,15,24,25,26,],[3,19,21,22,30,31,32,]),'assign':([0,],[4,]),'against':([0,],[5,]),'term':([0,12,14,15,24,25,26,],[6,6,6,6,6,6,6,]),'factor':([0,10,11,12,14,15,24,25,26,],[8,16,18,8,8,8,8,8,8,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> prog","S'",1,None,None,None),
  ('prog -> sentence','prog',1,'p_prog','ogengo.py',58),
  ('sentence -> formula','sentence',1,'p_sentence','ogengo.py',62),
  ('sentence -> assign','sentence',1,'p_sentence','ogengo.py',63),
  ('sentence -> against','sentence',1,'p_sentence','ogengo.py',64),
  ('assign -> VAR HA formula','assign',3,'p_assign1','ogengo.py',68),
  ('assign -> VAR NO VAR HA formula','assign',5,'p_assign2','ogengo.py',75),
  ('against -> VAR NI formula WO TASU','against',5,'p_against1','ogengo.py',84),
  ('against -> VAR KARA formula WO HIKU','against',5,'p_against1','ogengo.py',85),
  ('against -> VAR NO VAR NI formula WO TASU','against',7,'p_against2','ogengo.py',93),
  ('against -> VAR NO VAR KARA formula WO HIKU','against',7,'p_against2','ogengo.py',94),
  ('formula -> term','formula',1,'p_formula','ogengo.py',102),
  ('term -> term TASU factor','term',3,'p_term','ogengo.py',106),
  ('term -> term HIKU factor','term',3,'p_term','ogengo.py',107),
  ('term -> factor','term',1,'p_term','ogengo.py',108),
  ('factor -> NUMBER','factor',1,'p_factor_num','ogengo.py',117),
  ('factor -> VAR','factor',1,'p_factor_var1','ogengo.py',121),
  ('factor -> VAR NO VAR','factor',3,'p_factor_var2','ogengo.py',125),
]
